language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
#    - cubrid/9.3.0
    - vendor
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:~1.1.0"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"


before_script:
  # show some versions and env information
  - php -r "echo INTL_ICU_VERSION . \"\n\";"

  - |
    if [ $TRAVIS_PHP_VERSION = '5.6' ]; then
      PHPUNIT_FLAGS="--coverage-clover=coverage.clover"
    fi

script:
  - phpunit --bootstrap tests/bootstrap.php tests

after_script:
  - |
    if [ $TRAVIS_PHP_VERSION = '5.6' ]; then
      travis_retry wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi